---
showSupportUrl:         true
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    8
    requiredRam:        0.5
    internetCheckUrl:   https://geoip.ubuntu.com/lookup

    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - root
        - storage
        - ram

# GeoIP effectively disabled by setting style to "none" -- same as the real Kubuntu 26.04
# reference this was adapted from.
geoip:
    style:  "none"
    url:    "https://geoip.ubuntu.com/lookup"
    selector: "CountryCode"
